#!/usr/bin/env python3
import subprocess
import argparse
from config import cfg, cfg_init
    
parser = argparse.ArgumentParser()
parser.add_argument('--cfg', default='src/configs/unet.yaml', type=str)
args = parser.parse_args()

cfg_init(args.cfg)
nproc_per_node = len(cfg.TRAIN.GPUS)
cmd_dist = f'python3  -m torch.distributed.launch --nproc_per_node={nproc_per_node} src/main.py --cfg {args.cfg}'
cmd_single = f'python3 src/main.py --cfg {args.cfg}'
            
cmd = cmd_dist if cfg.PARALLEL.DDP else cmd_single
p = subprocess.Popen(cmd, shell=True)
p.communicate()

